version: 1

phases:
  install:
    runtime-versions:
      nodejs: 18.18.0
    commands:
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - ng build --prod

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/'
